version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: live-chat-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Main application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: live-chat-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/livechat?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:
