version: '3.8'

services:
  # MongoDB service for development
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  # Main application for development
  app:
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/livechat?authSource=admin
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
