version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:6.0
    container_name: live-chat-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Main application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: live-chat-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/livechat?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    # Remove volumes for production to prevent file system conflicts

volumes:
  mongodb_data:
