#!/bin/bash

# Script to set up GitHub Wiki for Live Chat Server
# This script provides instructions for setting up the wiki manually

echo "=== Live Chat Server Wiki Setup ==="
echo ""

echo "1. Navigate to your GitHub repository wiki:"
echo "   https://github.com/leonyonz/live-chat-server/wiki"
echo ""

echo "2. Create the following pages by copying content from docs/wiki/:"
echo ""
echo "   Home Page (Home.md):"
echo "   - Copy content from docs/wiki/Home.md"
echo "   - This becomes your main wiki page"
echo ""
echo "   Setup and Installation (Setup-and-Installation.md):"
echo "   - Copy content from docs/wiki/Setup-and-Installation.md"
echo ""
echo "   Configuration (Configuration.md):"
echo "   - Copy content from docs/wiki/Configuration.md"
echo ""
echo "   Deployment Guide (Deployment-Guide.md):"
echo "   - Copy content from docs/wiki/Deployment-Guide.md"
echo ""
echo "   Admin Dashboard Guide (Admin-Dashboard-Guide.md):"
echo "   - Copy content from docs/wiki/Admin-Dashboard-Guide.md"
echo ""
echo "   API Documentation (API-Documentation.md):"
echo "   - Copy content from docs/wiki/API-Documentation.md"
echo ""
echo "   Debugging Guide (Debugging-Guide.md):"
echo "   - Copy content from docs/wiki/Debugging-Guide.md"
echo ""
echo "   Changelog (Changelog.md):"
echo "   - Copy content from docs/wiki/Changelog.md"
echo ""

echo "3. Alternative: Use GitHub's web interface to create pages"
echo "   - Go to the wiki tab"
echo "   - Click 'New Page'"
echo "   - Set the page name (without .md extension)"
echo "   - Paste the content from the corresponding file in docs/wiki/"
echo "   - Save the page"
echo ""

echo "4. Once all pages are created, your wiki will be complete!"
echo ""
echo "Note: The wiki content already exists in your repository at docs/wiki/"
echo "      You just need to transfer it to the GitHub wiki system."
